name: build N push
on: push

jobs:
  build:
    name: ad-server action
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master

      - name: Build the Docker image
        run: docker build . -t ghcr.io/ryuhon/ad-server:latest

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: push
        run: docker push ghcr.io/ryuhon/ad-server:latest